plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'cn.morfans.chenjunyu19.mediavolume'
    compileSdk {
        version = release(36)
    }

    defaultConfig {
        applicationId "cn.morfans.chenjunyu19.mediavolume"
        minSdk 24
        targetSdk 36
        versionCode 20
        versionName "1.7.2"
    }

    buildTypes {
        release {
            optimization {
                enable true
            }
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
