plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace = 'cn.morfans.chenjunyu19.mediavolume'
    compileSdk = 37

    defaultConfig {
        applicationId = "cn.morfans.chenjunyu19.mediavolume"
        minSdk = 24
        targetSdk = 37
        versionCode = 21
        versionName = "1.7.3"
    }

    buildTypes {
        release {
            optimization {
                enable = true
            }
        }
    }

    dependenciesInfo {
        includeInApk = false
        includeInBundle = false
    }
}
